builders:
  codeLineBuilder:
    import: "package:task_1/task_1.dart"
    builder_factories: ["codeLineBuilder"]
    build_extensions: {".dart": [.g]}
    build_to: source
    auto_apply: root_package
    